In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [3]:
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [6]:
A.ndim
A.shape
A.size

9

In [9]:
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
A = np.array(a)
print(A)
print(A.size)
print(A.ndim)
print(A.shape)
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

C = np.dot(A,B)
print(C)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
2
(3, 4)
[[ 1  4]
 [ 5 12]
 [ 9 20]]
